### ISSUE TITLE
Missing "android.hardware.light-V1-ndk_platform"

### ISSUE THREAD

**Issue by nguyenanhgiau** [SoMainline/android-lights-hal#2]
Hi there,

I am going to integrate light service to AOSP on raspberry pi 4.
This project is based on GloDroid: https://github.com/GloDroid/glodroid_manifest
After following README, I always get the below error message:
```bash
error: hardware/st/lights-hal/Android.bp:1:1: "android.hardware.lights-service" depends on undefined module "android.hardware.light-V1-ndk_platform"
```
Could you please tell me what is wrong?
Thanks
Ricky

**Comment by MarijnS95** [comment]
Tell glodroid to track the right branch.
